import Head from 'next/head';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Joel Rivera | React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section classNane="bg-blue-600">
      <h1>Hello</h1>
        </section>

      </main>

    </div>
  );
}
